### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by BangBang-e** [BangBang-e/todo-app#1]
### 만들고자 하는 기능이 무엇인가요?
Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] Todo 컴포넌트 제작
2. [ ] Todo 컴포넌트를 렌더링 할 Todolist 제작
3. [ ] CREATE 기능 구현

### 예상 작업 시간
3h
